export const cartItems = [
  { name: 'Apple', price: 120, quantity: 3 },
  { name: 'Banana', price: 50, quantity: 5 },
  { name: 'Orange', price: 6, quantity: 2 },
  { name: 'PineApple', price: 2, quantity: 2 },
  { name: 'Coconut', price: 90, quantity: 2 },
  { name: 'Peach', price: 45, quantity: 2 },
  { name: 'Mango', price: 70, quantity: 4 },
  { name: 'Grapes', price: 30, quantity: 3 },
  { name: 'Watermelon', price: 120, quantity: 1 },
  { name: 'Cherry', price: 80, quantity: 2 },
  { name: 'Pear', price: 55, quantity: 3 },
  { name: 'Kiwi', price: 60, quantity: 2 },
  { name: 'Strawberry', price: 40, quantity: 5 },
  { name: 'Blueberry', price: 75, quantity: 2 },
  { name: 'Raspberry', price: 90, quantity: 3 },
  { name: 'Pomegranate', price: 100, quantity: 1 },
  { name: 'Blackberry', price: 55, quantity: 4 },
  { name: 'Apricot', price: 35, quantity: 3 },
  { name: 'Plum', price: 30, quantity: 2 },
  { name: 'Lemon', price: 10, quantity: 5 },
  { name: 'Lime', price: 15, quantity: 2 },
  { name: 'Cantaloupe', price: 80, quantity: 1 },
  { name: 'Honeydew', price: 70, quantity: 2 },
  { name: 'Fig', price: 50, quantity: 3 },
  { name: 'Guava', price: 65, quantity: 2 },
]
